src/Entity/TrabajadorCredencial.php
<?php

namespace App\Entity;

use App\Repository\TrabajadorCredencialRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Table(name: 'app_trabajador_credencial')]
#[ORM\Entity(repositoryClass: TrabajadorCredencialRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_USUARIO', fields: ['usuario'])]
#[ORM\HasLifecycleCallbacks]
class TrabajadorCredencial implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\OneToOne(inversedBy: 'credencial', targetEntity: Trabajador::class)]
    #[ORM\JoinColumn(name: 'id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    private ?Trabajador $trabajador = null;

    #[ORM\Column(type: 'string', length: 50, unique: true)]
    private ?string $usuario = null;

    #[ORM\Column(type: 'string', length: 60)]
    private ?string $contrasena = null;

    #[ORM\Column(name: 'es_admin', type: 'boolean')]
    private bool $admin = false;

    #[ORM\Column(type: 'text', length: 120, nullable: false)]
    private string $navegador = '';

    #[ORM\Column(type: 'datetime', options: ["default" => "CURRENT_TIMESTAMP"])]
    private DateTime $creado;

    #[ORM\Column(type: 'json')]
    private array $ultima_conexion = [];

    #[ORM\Column(type: 'datetime', options: ["default" => "CURRENT_TIMESTAMP"])]
    private DateTime $ultimo_acceso;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private bool $forzar_cambio_contrasena = false;

    #[ORM\Column(type: 'string', length: 40, nullable: true)]
    private ?string $salt = null;

    public function __construct()
    {
        $this->creado = new DateTime();
        $this->ultimo_acceso = new DateTime();
    }

    public function __toString(): string
    {
        return $this->usuario;
    }

    public function getUsuario(): ?string
    {
        return $this->usuario;
    }

    public function setUsuario(string $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getContrasena(): ?string
    {
        return $this->contrasena;
    }

    public function setContrasena(?string $contrasena): self
    {
        if ($contrasena)
            $this->contrasena = $contrasena;

        return $this;
    }

    public function getAdmin(): bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): TrabajadorCredencial
    {
        $this->admin = $admin;
        return $this;
    }

    public function isAdmin(): bool
    {
        return $this->admin;
    }

    public function getNavegador(): string
    {
        return $this->navegador;
    }

    public function setNavegador(string $navegador): TrabajadorCredencial
    {
        $this->navegador = $navegador;
        return $this;
    }

    public function getCreado(): DateTime
    {
        return $this->creado;
    }

    public function setCreado(DateTime $creado): TrabajadorCredencial
    {
        $this->creado = $creado;
        return $this;
    }

    public function getUltimoAcceso(): DateTime
    {
        return $this->ultimo_acceso;
    }

    public function setUltimoAcceso(DateTime $ultimo_acceso): TrabajadorCredencial
    {
        $this->ultimo_acceso = $ultimo_acceso;
        return $this;
    }

    public function getUltimaConexion(): array
    {
        return $this->ultima_conexion;
    }

    public function setUltimaConexion(array $ultima_conexion): TrabajadorCredencial
    {
        $this->ultima_conexion = $ultima_conexion;
        return $this;
    }

    public function getForzarCambioContrasena(): bool
    {
        return $this->forzar_cambio_contrasena;
    }

    public function setForzarCambioContrasena(bool $forzar_cambio_contrasena): TrabajadorCredencial
    {
        $this->forzar_cambio_contrasena = $forzar_cambio_contrasena;
        return $this;
    }

    public function getTrabajador(): ?Trabajador
    {
        return $this->trabajador;
    }

    public function setTrabajador(?Trabajador $trabajador): self
    {
        $this->trabajador = $trabajador;

        return $this;
    }

    #[Pure] public function getPersona(): ?Persona
    {
        return $this->getTrabajador()?->getPersona();
    }

    #[Pure] public function getNombre(): ?string
    {
        return $this->getPersona()?->getNombre();
    }

    #[Pure] public function getCargo(): ?string
    {
        return $this->getTrabajador()?->getCargo();
    }

    #[Pure] public function getEstructura(): ?Estructura
    {
        return $this->getTrabajador()?->getEstructura();
    }

    #[Pure] public function getUsername(): ?string
    {
        return $this->usuario;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->contrasena;
    }

    #[Pure] public function getUserIdentifier(): string
    {
        return $this->getUsuario();
    }

    #[Pure] public function getRoles(): array
    {
        $roles = ['ROLE_USER'];

        if ($this->isAdmin())
            $roles[] = 'ROLE_ADMIN';

        return $roles;
    }

    public function setSalt(string $salt): static
    {
        $this->salt = $salt;
        return $this;
    }

    public function getSalt(): ?string
    {
        return $this->salt;
    }

    public function eraseCredentials()
    {
        return null;
    }

    #[Pure] public function getHabilitado(): ?bool
    {
        return $this->getTrabajador()?->getHabilitado();
    }
}

templates/homer-theme/base.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}Bienvenido!{% endblock %} | Sistema de Gestión Paquetería Express</title>
    <!-- Vendor styles -->
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/fontawesome/css/font-awesome.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/metisMenu/dist/metisMenu.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/animate.css/animate.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/bootstrap/dist/css/bootstrap.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/select2-3.5.2/select2.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/select2-3.5.2/select2-bootstrap.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/sweetalert/lib/sweet-alert.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/toastr/build/toastr.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/vendor/ladda/dist/ladda-themeless.min.css') }}"/>
    <!-- App styles -->
    <link rel="stylesheet" href="{{ asset('homer-theme/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/fonts/pe-icon-7-stroke/css/helper.css') }}"/>
    <link rel="stylesheet" href="{{ asset('homer-theme/styles/static_custom.css') }}">
    <link rel="stylesheet" href="{{ asset('homer-theme/styles/style.css') }}">
    <link rel="manifest" href="{{ asset('manifest.json') }}">

    {% block stylesheets %}{% endblock %}
</head>
<body class="{% block bodyClass %}{% endblock %}">
{% block layout %}{% endblock %}

<!-- Vendor scripts -->
<script src="{{ asset('homer-theme/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/jquery-validation/messages_es.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/select2-3.5.2/select2.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/select2-3.5.2/select2_locale_es.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/sweetalert/lib/sweet-alert.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/readmore/readmore.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/toastr/build/toastr.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/ladda/dist/spin.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/ladda/dist/ladda.min.js') }}"></script>
<script src="{{ asset('homer-theme/vendor/ladda/dist/ladda.jquery.min.js') }}"></script>
<!-- App scripts -->
<script src="{{ asset('homer-theme/scripts/homer.min.js') }}"></script>
<script src="{{ asset('app.min.js') }}"></script>

{% if app.request.method == 'GET' %}
    <script type="text/javascript">
        {% set referer = app.request.headers.get('referer') %}
        {% set from_search = app.session.has('from-search') ?? false %}
        {% set flashes = ('buscar' in referer or not from_search) ? app.session.flashbag.get('toastr') : app.session.flashbag.peek('toastr') %}
        {% for flash in flashes %}
        {{ flash|raw }}
        {% endfor %}
    </script>
{% endif %}


{% block javascripts %}{% endblock %}
</body>
</html>

templates/homer-theme/change_password.html.twig
{% extends 'homer-theme/base.html.twig' %}
{% block bodyClass %}blank{% endblock %}
{% block layout %}
    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <h3>CAMBIO DE CONTRASEÑA</h3>
                </div>
                <div class="hpanel">
                    {{ form_start(form) }}
                    <div class="panel-body">
                        <div class="form-group">
                            {{ form_label(form.usuario) }}
                            {{ form_widget(form.usuario) }}
                            {{ form_help(form.usuario) }}
                            {{ form_errors(form.usuario) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.contrasena.first,null,{'label_attr':{'class': 'control-label required'}}) }}
                            {{ form_widget(form.contrasena.first,{required:true}) }}
                            {{ form_help(form.contrasena.first) }}
                            {{ form_errors(form.contrasena.first) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.contrasena.second,null,{'label_attr':{'class': 'control-label required'}}) }}
                            {{ form_widget(form.contrasena.second,{required:true}) }}
                            {{ form_help(form.contrasena.second) }}
                            {{ form_errors(form.contrasena.second) }}
                        </div>
                        <button class="btn btn-success btn-block ladda-button" data-style="zoom-in">Cambiar</button>
                        <a class="btn btn-default btn-block" href="{{ path('app_logout') }}">Cancelar</a>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                Sistema de Gestión Paquetería Express<br/>
                {{ 'now'|date('Y') }} | Derecho de autor Centro Principal Tecnológico Postal (<strong>CPTP</strong>)
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        $(function () {
            let form = $('form');
            let l = $('.ladda-button').ladda();
            form.validate({
                submitHandler: function () {
                    l.ladda('start');
                    return true;
                }
            });
        });
    </script>
{% endblock %}

templates/homer-theme/layout.html.twig
{% extends 'homer-theme/base.html.twig' %}

{% use 'homer-theme/components/header.html.twig' %}
{% use 'homer-theme/components/menu.html.twig' %}
{% use 'homer-theme/components/splash.html.twig' %}
{% use 'homer-theme/components/wrapper.html.twig' %}

{% block bodyClass %}fixed-navbar fixed-sidebar{% endblock %}
{% block layout %}
    {% block splash %}{{ parent() }}{% endblock %}
    {% block header %}{{ parent() }}{% endblock %}
    {% block menu %}{{ parent() }}{% endblock %}
    {% block wrapper %}{{ parent() }}{% endblock %}
{% endblock %}

templates/homer-theme/login.html.twig
{% extends 'homer-theme/base.html.twig' %}
{% block bodyClass %}blank{% endblock %}
{% block layout %}
    <div class="back-link">
        <a href="{{ path('app_home') }}" class="btn btn-primary">Volver a la pagina de inicio</a>
    </div>

    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <h3>POR FAVOR INGRESE SUS DATOS</h3>
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <form method="post">
                            {% if error %}
                                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                            {% endif %}
                            <div class="form-group">
                                <label class="control-label" for="username">Usuario</label>
                                <input type="text" placeholder="Nombre de usuario"
                                       title="Por favor, introduzca su nombre de usuario" required autofocus
                                       value="{{ last_username }}" name="usuario" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="password">Contraseña</label>
                                <input type="password" title="Por favor, introduzca su contraseña" placeholder="******"
                                       required="" value="" name="password" id="inputPassword" class="form-control">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="remember_me" name="_remember_me" class="i-checks">
                                    Recordar sesión
                                </label>
                                <p class="help-block small">(Si es una computadora privada)</p>
                            </div>
                            <button class="btn btn-success btn-block ladda-button"
                                    data-style="zoom-in">Iniciar sesión
                            </button>
                            {# <a class="btn btn-default btn-block" href="#">Register</a> #}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                Sistema de Gestión Paquetería Express<br/>
                {{ 'now'|date('Y') }} | Derecho de autor Centro Principal Tecnológico Postal (<strong>CPTP</strong>)
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        $(function () {
            let form = $('form');
            let l = $('.ladda-button').ladda();
            form.validate({
                submitHandler: function () {
                    l.ladda('start');
                    return true;
                }
            });
        });
    </script>
{% endblock %}

templates/homer-theme/profile.html.twig
{% extends 'homer-theme/layout.html.twig' %}
{% block body %}
    <div class="hpanel blog-box">

        <div class="panel-body">
            {{ form_start(form) }}
            <div class="row">
                <div class="col-md-2 border-right">
                    <img src="{{ asset('homer-theme/images/profile.png') }}" width="150px">
                </div>
                <div class="col-md-5">
                    {{ form_label(form.persona) }}
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.persona.numero_identidad) }}</div>
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.cargo) }}</div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.persona.nombre_primero) }}</div>
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.persona.nombre_segundo) }}</div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.persona.apellido_primero) }}</div>
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.persona.apellido_segundo) }}</div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-12">{{ form_row(form.credencial.usuario) }}</div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.credencial.contrasena.first) }}</div>
                        <div class="col-xs-6 col-sm-6">{{ form_row(form.credencial.contrasena.second) }}</div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-12">{{ form_row(form.estructura) }}</div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-12">{{ form_row(form.grupos) }}</div>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-sm btn-success">{{ 'guardar'|trans({},'admin') }}</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}