src/Entity/Trabajador.php
<?php

namespace App\Entity;

use App\Entity\Nomenclador\Grupo;
use App\Repository\TrabajadorRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'app_trabajador')]
#[ORM\Entity(repositoryClass: TrabajadorRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_PERSONA_ID', columns: ['persona_id'])]
#[ORM\Index(columns: ['estructura_id'], name: 'IDX_ESTRUCTURA_ID')]
class Trabajador extends _Entity_
{
    #[ORM\OneToOne(targetEntity: Persona::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'persona_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[Assert\Valid]
    private Persona $persona;

    #[ORM\OneToOne(mappedBy: 'trabajador', targetEntity: TrabajadorCredencial::class, cascade: ['persist'])]
    #[Assert\Valid]
    private ?TrabajadorCredencial $credencial = null;

    #[ORM\ManyToOne(targetEntity: Estructura::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Estructura $estructura;

    #[ORM\ManyToMany(targetEntity: Nomenclador::class)]
    #[ORM\JoinTable(name: 'app_trabajador_grupo_asignado')]
    #[ORM\JoinColumn(name: 'trabajador_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'grupo_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[Assert\Valid]
    private Collection $grupos;

    #[ORM\Column(type: 'string', length: 100)]
    private string $cargo;

    #[ORM\Column(type: 'boolean')]
    private bool $habilitado = true;

    #[Pure] public function __construct()
    {
        $this->persona = new Persona();
        $this->grupos = new ArrayCollection();
    }

    #[Pure] public function __toString(): string
    {
        return (string)'';
    }

    /**
     * @return Collection|Grupo[]
     */
    public function getGrupos(): Collection
    {
        return $this->grupos;
    }

    public function addGrupo(Grupo $grupo): self
    {
        if (!$this->grupos->contains($grupo)) {
            $this->grupos[] = $grupo;
        }

        return $this;
    }

    public function removeGrupo(Grupo $grupo): self
    {
        $this->grupos->removeElement($grupo);

        return $this;
    }

    public function getCargo(): ?string
    {
        return $this->cargo;
    }

    public function setCargo(string $cargo): self
    {
        $this->cargo = $cargo;

        return $this;
    }

    public function getHabilitado(): ?bool
    {
        return $this->habilitado;
    }

    public function setHabilitado(bool $habilitado): self
    {
        $this->habilitado = $habilitado;

        return $this;
    }

    public function getPersona(): ?Persona
    {
        return $this->persona;
    }

    public function setPersona(?Persona $persona): self
    {
        $this->persona = $persona;

        return $this;
    }

    public function getCredencial(): ?TrabajadorCredencial
    {
        return $this->credencial;
    }

    public function setCredencial(?TrabajadorCredencial $credencial): self
    {
        // unset the owning side of the relation if necessary
        if ($credencial === null && $this->credencial !== null) {
            $this->credencial->setTrabajador(null);
        }

        // set the owning side of the relation if necessary
        if ($credencial !== null && $credencial->getTrabajador() !== $this) {
            $credencial->setTrabajador($this);
        }

        $this->credencial = $credencial;

        return $this;
    }

    public function getEstructura(): ?Estructura
    {
        return $this->estructura;
    }

    public function setEstructura(?Estructura $estructura): self
    {
        $this->estructura = $estructura;

        return $this;
    }

    #[Pure] public function getNombre(): string
    {
        return $this->getPersona()->getNombre();
    }

    #[Pure] public function getNombreCompleto(): string
    {
        return $this->getPersona()->getNombreCompleto();
    }

    public function getSexo(): string
    {
        return $this->getPersona()->getSexo();
    }

    public function getNacimiento(): DateTime
    {
        return $this->getPersona()->getNacimiento();
    }

    public function setDatoCredencial($username, $password, bool $isAdmin = false): self
    {
        $credencial = new TrabajadorCredencial();
        $credencial->setUsuario($username);
        $credencial->setContrasena($password);
        $credencial->setAdmin($isAdmin);

        $this->setCredencial($credencial);
        return $this;
    }

    public function setDatoPersona(
        string $numeroID,
        string $nombrePrimero,
        string $nombreSegundo,
        string $apellidoPrimero,
        string $apellidoSegundo,
        Pais   $pais,
    ): Trabajador
    {
        $persona = new Persona();

        if ($pais->getCodigoAduana() === Pais::PRINCIPAL)
            $persona->setNumeroIdentidad($numeroID);
        else
            $persona->setNumeroPasaporte($numeroID);

        $persona->setNombrePrimero($nombrePrimero);
        $persona->setNombreSegundo($nombreSegundo);
        $persona->setApellidoPrimero($apellidoPrimero);
        $persona->setApellidoSegundo($apellidoSegundo);
        $persona->setPais($pais);

        $this->setPersona($persona);

        return $this;
    }

    public function getMenus(): Collection
    {
        $menus = [];
        foreach ($this->getGrupos() as $grupo) {
            $menus = array_merge($menus, $grupo->getMenus()->toArray());
        }
        return new ArrayCollection($menus);
    }

    #[Pure] public function hasCredentials(): bool
    {
        return $this->credencial && $this->credencial->getUsuario();
    }
}

src/Controller/Envio/FacturaController.php
<?php


namespace App\Controller\Envio;

use App\Entity\Envio\Envio;
use App\Entity\Envio\EnvioAduana;
use App\Entity\Envio\Factura;
use App\Entity\Envio\FacturaConsecutivo;
use App\Entity\Envio\FacturaTraza;
use App\Entity\Envio\Saca;
use App\Entity\Estructura;
use App\Entity\Nomenclador;
use App\Entity\Nomenclador\EstructuraTipo;
use App\Entity\Nomenclador\Grupo;
use App\Entity\Persona;
use App\Entity\Trabajador;
use App\Entity\TrabajadorCredencial;
use App\Manager\EnvioManager;
use App\Manager\FacturaManager;
use App\Repository\Envio\FacturaRepository;
use App\Repository\NomencladorRepository;
use App\Repository\Envio\SacaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use JMS\Serializer\SerializerBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\throwException;

#[Route('/factura')]
class FacturaController extends AbstractController
{
    public function __construct(
        private SacaRepository         $sacaRepository,
        private FacturaManager         $facturaManager,
        private NomencladorRepository  $nomencladorRepository,
        private FacturaRepository      $facturaRepository,
        private EntityManagerInterface $entityManager,
        private EnvioManager           $envioManager
    )
    {
    }

    #[Route('/recepcionar', name: 'procesar_factura', methods: ['GET'])]
    public function procesarFactura()
    {

        return $this->render('factura/recepcionar.html.twig', []);
    }

    #[Route('/find-sacas-factura', name: 'find_sacas_factura', options: ["expose" => true], methods: ['POST'])]
    public function findSacasFactura(Request $request)
    {
        $noFactura = $request->get('noFactura');
        $sacas = $this->facturaRepository->findSacasNoFacturaAndEstado($noFactura);
        $envios = $this->facturaRepository->findEnviosNoFacturaAndEstado($noFactura);
        $anomalias = $this->nomencladorRepository->findByChildren('APP_SACA_ANOMALIA');
        $anomaliasE = $this->nomencladorRepository->findByChildren('APP_ENVIO_ANOMALIA');

        $html = $sacas || $envios ? $this->renderView('factura/sacas.html.twig', [
            'sacas' => $sacas,
            'envios' => $envios,
            'anomalias' => $anomalias->toArray(),
            'anomaliasE' => $anomaliasE->toArray(),
            'noFactura' => $noFactura]) : 'null';

        return new Response($html);
    }

    #[Route('/recepcionar-sacas-factura', name: 'recepcionar_sacas_factura', options: ["expose" => true], methods: ['POST'])]
    public function recepcionarSacasFactura(Request $request)
    {
        $noFactura = $request->get('noFactura');
        $sacas = $request->get('sacas') ?? [];
        $envios = $request->get('envios') ?? [];
        $todos = filter_var($request->get('todos'), FILTER_VALIDATE_BOOLEAN);
        $factura = $this->facturaRepository->getFacturaByNoFactura($noFactura);
        $estado = $this->nomencladorRepository->findOneByCodigo('APP_SACA_ESTADO_RECIBIDA');

        /** @var TrabajadorCredencial $credencial */
        $credencial = $this->getUser();

        foreach ($sacas as $id) {
            $saca = $this->sacaRepository->find($id);
            $saca->setEstado($estado);

            $this->entityManager->persist($saca);
            $this->entityManager->flush();
        }

        foreach ($envios as $id) {
            $this->envioManager->cambiarEstado($id, $credencial);
        }

        if ($todos) {
            $estado = $this->nomencladorRepository->findOneByCodigo('APP_FACTURA_ESTADO_RECIBIDA');
            $factura->setEstado($estado);
            $this->entityManager->persist($factura);
            $this->entityManager->flush();

            $this->facturaManager->createTraza($factura, $credencial);
        }
        return JsonResponse::fromJsonString('"Factura recibida correctamente"');
    }

    #[Route('/crear', name: 'crear_factura')]
    public function CrearFactura(): Response
    {
        $choferes = new ArrayCollection();
        $empresas = new ArrayCollection();
        $em = $this->getDoctrine()->getManager();
        /** @var Trabajador $user */
        $user = $this->getUser();

        $osde = $user->getEstructura()->searchParentsByTipo(
            $em->getRepository(EstructuraTipo::class)->findOneByCodigo(EstructuraTipo::OSDE)
        );

        /** @var Estructura $empresa */
        foreach ($osde->getChildren()->toArray() as $empresa) {

            if ($empresa->getChildren()) {
                foreach ($empresa->getChildren()->toArray() as $oficina) {
                    //dump($oficina);exit();
                    /** @var Estructura $oficina */
                    foreach ($oficina->getTipos()->toArray() as $item) {
                        /** @var Nomenclador $item */
                        if ($item->getCodigo() == 'OFICINA_CCP' || $item->getCodigo() == 'OFICINA_CDD') {
                            $empresas->add($oficina);

                        }
                    }
                }
            }

        }

        /** @var Nomenclador $nom */
        $nom = $em->getRepository(Nomenclador::class)->findOneByCodigo('APP_TIPO_VEHICULO');
        $vehiculos = $nom->getChildren()->getValues();

        /** @var Trabajador $trabajador */
        $trabajador = $em->getRepository(Trabajador::class)->findAll();
        //$choferes = $trabajador->getPersona();

        foreach ($trabajador as $item) {
            /** @var Trabajador $item */
            foreach ($item->getGrupos()->getValues() as $g) {
                /** @var Grupo $g */
                if ($g->getCodigo() == 'GRUPO_CHOFER') {
                    $id = $item->getPersona()->getId();
                    /** @var Persona $c */
                    $c = $em->getRepository(Persona::class)->find($id);
                    $choferes->add($c);
                }
            }

        }

        return $this->render('factura/crear_factura.html.twig', [
            'findAll' => $empresas,
            'vehiculos' => $vehiculos,
            'choferes' => $choferes

        ]);
    }

    #[Route('/AnnadirSaca', options: ["expose" => true], name: 'AnnadirSaca', methods: ['POST'])]
    public function Annadir(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        if ($request->isXmlHttpRequest()) {
            $sello = $request->request->get('codTracking');
            $oficina_dest = $request->request->get('oficina_dest');

            /** @var Trabajador $user */
            $user = $this->getUser();

            $empresa = $user->getEstructura()->searchParentsByTipo(
                $em->getRepository(EstructuraTipo::class)->findOneByCodigo(EstructuraTipo::EMPRESA)
            );

            /** @var Estructura $ofic_dest */
            $ofic_dest = $em->getRepository(Estructura::class)->find($oficina_dest);

            /** @var Saca $saca */
            $saca = $em->getRepository(Saca::class)->findOneBy(['sello' => $sello]);

            if ($saca == null) {
                /** @var Envio $saca */
                $saca = $em->getRepository(Envio::class)->findOneBy(['cod_tracking' => $sello]);

                if ($saca != null) {
                    if ($saca->getEstado()->getCodigo() != 'APP_ENVIO_ESTADO_CLASIFICADO' && $saca->getEstado()->getCodigo() != 'APP_ENVIO_ESTADO_FACTURADO') {
                        if ($saca->getMunicipio()->getId() == $ofic_dest->getMunicipio()->getId()) {
                            $id = $saca->getId();
                            $cod = $saca->getCodTracking();
                            $peso = $saca->getPeso();

                            $serializer = SerializerBuilder::create()->build();
                            $miRespuestaJson = $serializer->serialize(['id' => $id, 'cod' => $cod, 'peso' => $peso], "json");

                            /** @var EnvioAduana $envio_aduana */
                            $envio_aduana = $em->getRepository(EnvioAduana::class)->findOneBy(['envio' => $id]);
                            //dump($envio_aduana);exit();

                            if ($envio_aduana != null) {
                                if ($envio_aduana->getDatosDespacho() == null) {
                                    $url = "https://sua.aduana.cu/GINASUA/serviciosExternos?wsdl";

                                    if ($this->envioManager->verificarConectAduana($url) == 1) {
                                        if ($this->envioManager->addDespachoAduanaEnvio($url, $envio_aduana->getId(), $cod, $empresa)) {
                                            return JsonResponse::fromJsonString($miRespuestaJson);
                                        } else {
                                            $respuesta = 'El servicio del despacho de la aduana no está funcionando, por favor intentelo mas tarde.';
                                        }
                                    } else {
                                        $respuesta = 'La conexión con el servicio de aduana esta tardando mucho, por favor intentelo mas tarde.';
                                    }
                                } else {
                                    return JsonResponse::fromJsonString($miRespuestaJson);
                                }
                            } else {
                                $respuesta = 'El envío aduana no exite';
                            }
                        } else {
                            $respuesta = 'El envío esta mal reeencaminado';
                        }
                    } else {
                        $respuesta = 'El envío ya esta clasificado o facturado';
                    }
                } else {

templates/factura/crear_factura.html.twig
{% extends 'homer-theme/layout.html.twig' %}

{% block title %}Crear Factura{% endblock %}
{% block panel_title %}Generación de factura de entrega{% endblock %}
{% block panel_body %}

    <div id="miForm">
        <div class="row col-md-12 m-b">

            <legend><h5>Destino de la factura</h5></legend>

            <div class="col-md-5">
                <label class="form-label">Oficina de destino</label>
                <select id="select_oficinas_factura" class="form-control input-sm select2" aria-label="Oficinas">
                    <option  value="0" selected>Seleccione</option>
                    {% for estructura in findAll %}

                        <option value="{{ estructura.id }}">{{ estructura }}</option>

                    {% endfor %}
                </select>
                <div id="mensaje_oficina"></div>
            </div>

        </div>

        <div class="row col-md-12 m-b">

            <legend><h5>Asignación de las sacas a la factura</h5></legend>

            <div class="col-md-6">
                <label class="form-label">Código de tracking  o Sello de la saca</label>
                <input id="input_sello" type="text">
            </div>
            <div class="col-md-2">
                <button class="btn btn-info" onclick="AgregarSaca()" id="button_anndir_sacas">
                    <i class="fa fa-plus"></i>
                    Añadir
                </button>
            </div>

            <br><br><br>

            <div class="col-md-8">
                <table class="table table-hover table-bordered table-striped" id="tabla_sacas">
                    <thead>
                    <tr>
                        <th>Código de tracking o Sello</th>
                        <th>Peso</th>
                    </tr>
                    </thead>
                    <tbody id="resultado">

                    </tbody>
                </table>
                <div id="mensaje_tabla"></div>
            </div>


        </div>

        <div class="row col-md-12 m-b">

            <legend><h5>Datos para generar la factura</h5></legend>

            <div class="col-md-3">
                <label class="form-label">Tipo de vehículo</label>
                <select id="select_tipo_vehiculo" class="form-control input-sm select2" aria-label="Tipo de vehiculo">
                    <option  value="0" selected>Seleccione</option>
                    {% for v in vehiculos %}

                        <option value="{{ v.id }}">{{ v.nombre }}</option>

                    {% endfor %}

                </select>
                <div id="mensaje_tipo_vehiculo"></div>
            </div>

            <div class="col-md-2">
                <label class="form-label">Chapa</label>
                <input id="input_chapa" class="form-control input-sm" type="text" style="text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();">
                <div id="mensaje_chapa"></div>
            </div>

            <div class="col-md-3">
                <label class="form-label">Choferes</label>
                <select id="select_choferes" class="form-control input-sm select2" aria-label="Choferes">
                    <option  value="0" selected>Seleccione</option>
                    {% for item in choferes %}

                        <option value="{{ item.id }}">{{ item.nombrecompleto }}</option>

                    {% endfor %}
                </select>
                <div id="mensaje_choferes"></div>
            </div>

        </div>

        <hr>

        <div class="row col-md-12 m-b">

            <div class="col-auto" id="botones">
                <button class="btn btn-success" onclick="GuardarFactura()" id="button_crear_factura">Crear Factura</button>

                <a rel="nofollow" id="generar_factura" href="#" class="btn btn btn-primary">Generar Factura</a>

            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
    <script src="{{ path('fos_js_routing_js',{ callback: 'fos.Router.setData' }) }}"></script>

    <script src="{{ asset('js/factura.js') }}"></script>

{% endblock %}

templates/factura/imprimir_factura.html.twig
{% extends 'homer-theme/layout.html.twig' %}

{% block panel_body %}
    <div id="printableArea">
        <div class="col-md-12">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                <tr>
                    <td colspan="4" align="center">Factura Integrada de Envíos y Sacas</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Fecha: {{ fecha }}
                    </td>
                    <td>
                        Origen: {{ factura.origen }}
                    </td>
                    <td>
                        Factura: {{ factura.numerofactura }}
                    </td>
                    <td>
                        Código: {{ factura.codigofactura }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Despacho:
                    </td>
                    <td colspan="2">
                        Destino: {{ factura.destino }}
                    </td>
                    <td>
                        Chapa: {{ factura.chapavehiculo }}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <label>Relación de Sacas</label>
        </div>
        <div class="col-md-12">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                <tr>
                    <th>Consecutivo</th>
                    <th>Código</th>
                    <th>Sello</th>
                    <th>Peso(Kg)</th>
                    <th>Cantidad envíos</th>
                    <th>Número de despacho</th>
                    <th>Peso de los envíos</th>
                </tr>
                </thead>
                <tbody>
                {% for item in sacas %}
                    <tr>
                        <th></th>
                        <th>{{ item.codigo }}</th>
                        <th>{{ item.sello }}</th>
                        <th>{{ item.peso }}</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                {% endfor %}
                {% for item in envios %}
                    <tr>
                        <th></th>
                        <th></th>
                        <th>{{ item.codTracking }}</th>
                        <th>{{ item.peso }}</th>
                        <th>1</th>
                        <th></th>
                        <th></th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <label>Peso total de las sacas: </label>
        </div>


    </div>
    <div class="col-sm-12">
        <input type="button" onclick="printDiv('printableArea')" value="Imprimir" class="btn btn-primary"/>
        <a rel="nofollow" href="{{ path('crear_factura') }}" class="btn btn btn-default">Volver</a>
    </div>


{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
    <script src="{{ path('fos_js_routing_js',{ callback: 'fos.Router.setData' }) }}"></script>

    <script>

        function printDiv(divName) {
            var printContents = document.getElementById(divName).innerHTML;
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print();

            document.body.innerHTML = originalContents;
        }
    </script>

{% endblock %}

templates/factura/sacas.html.twig
{% block panel_body %}
    <div class="row col-md-12 m-b">

        <div class="well well-lg">

            <p style="border-bottom:1px solid #000000;"><strong>VALIJAS PRESENTES EN LA FACTURA</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {% for saca in sacas %}
                {% if saca.estado.codigo == 'APP_SACA_ESTADO_RECIBIDA' %}

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="panelSaca_{{saca.id}}">
                    <label class="form-label">SACA No. <span class="text-info">[{{ saca.sello }}]</span> código <span class="text-info">[{{saca.codigo}}]</span> en estado <span class="text-info">[{{ saca.estado.nombre }}]</span> &nbsp; + &nbsp;
                        <span class="text-danger">                            Irregularidades [
                            {% for key, irr in saca.observaciones %}
                                {{ key }}:{{ irr }},
                            {% endfor %}
                            ]</span>
                    </label>
                </div>
            </div>
            {% else %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="panelSaca_{{saca.id}}">

                        <input class="form-check-input checkbox-sacas" type="checkbox" value="{{saca.id}}" id="checkSaca_{{saca.id}}" checked>
                        <label class="form-label">SACA No. <span class="text-info">[{{ saca.sello }}]</span> código <span class="text-info">[{{saca.codigo}}]</span> en estado <span class="text-info">[{{ saca.estado.nombre }}]</span> &nbsp; + &nbsp;
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{saca.id}}" aria-expanded="false" aria-controls="collapse{{saca.id}}" class="collapsed collapse{{saca.id}}">
                                Irregularidades </a></label>

                    </div>
                    <div id="collapse{{saca.id}}" class="panel-collapse collapse collapse{{saca.id}}" role="tabpanel" aria-labelledby="panelSaca_{{saca.id}}" aria-expanded="false">
                        <div class="panel-body" id="anomaliaslist{{saca.id}}">
                            {% for an in anomalias %}
                                <div class="col-md-12" style="margin-bottom: 10px;">
                                    <div class="col-md-4">
                                        <input class="form-check-input check-anomalia {{an.codigo}}" type="checkbox" value="{{saca.id}}" >
                                        <label class="form-label {{an.codigo}}">{{an.nombre}}</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input class="form-control {{an.codigo}}" type="text" value="" id="{{saca.id}}_anomalia_{{an.codigo}}">
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="pull-right" style="margin-top: 25px;">
                                <button class="ladda-button btn btn-primary" data-style="expand-left" onclick="guardarAnomalia('{{ saca.id }}')" id="btn-anomalia-saca-{{ saca.id }}"> <span class="ladda-label"><i class="fa fa-check"></i> Guardar</span><span class="ladda-spinner"></span></button>
                            </div>

                        </div>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        </div>

        <!----------------- ENVIOS --------------------->
        <div class="well well-lg">

            <p style="border-bottom:1px solid #000000;"><strong>ENVIOS PRESENTES EN LA FACTURA</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {% for envio in envios %}
                {% if envio.estado.codigo != 'APP_ENVIO_ESTADO_FACTURADO' %}

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="panelenvio_{{envio.id}}">
                    <label class="form-label">Envio codigo <span class="text-info">[{{ envio.CodTracking }}]</span> peso <span class="text-info">[{{envio.peso}}]</span> en estado <span class="text-info">[{{ envio.estado.nombre }}]</span> &nbsp; + &nbsp;
                        <a data-toggle="collapse" data-parent="#accordion" href="#ecollapse{{envio.id}}" aria-expanded="false" aria-controls="ecollapse{{envio.id}}" class="collapsed">
                            Irregularidades </a></label>
                </div>
            </div>
            {% else %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="panelenvio_{{envio.id}}">

                        <input class="form-check-input checkbox-envios" type="checkbox" value="{{envio.id}}" id="checkenvio_{{envio.id}}" checked>
                        <label class="form-label">Envio codigo <span class="text-info">[{{ envio.CodTracking }}]</span> peso <span class="text-info">[{{envio.peso}}]</span> en estado <span class="text-info">[{{ envio.estado.nombre }}]</span> &nbsp; + &nbsp;
                            <a data-toggle="collapse" data-parent="#accordion" href="#ecollapse{{envio.id}}" aria-expanded="false" aria-controls="ecollapse{{envio.id}}" class="collapsed ecollapse{{envio.id}}">
                                Irregularidades </a></label>

                    </div>
                    <div id="ecollapse{{envio.id}}" class="panel-collapse collapse ecollapse{{envio.id}}" role="tabpanel" aria-labelledby="panelenvio_{{envio.id}}" aria-expanded="false">
                        <div class="panel-body" id="envioanomaliaslist{{envio.id}}">
                            {% for an in anomaliasE %}
                                <div class="col-md-12" style="margin-bottom: 10px;">
                                    <div class="col-md-4">
                                        <input class="form-check-input check-anomalia {{an.codigo}}" type="checkbox" value="{{an.codigo}}" >
                                        <label class="form-label {{an.codigo}}">{{an.nombre}}</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input class="form-control {{an.codigo}}" type="text" value="" id="{{envio.id}}_anomalia_{{an.codigo}}">
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="pull-right" style="margin-top: 25px;">
                                <button class="ladda-button btn btn-primary" data-style="expand-left" onclick="guardarAnomaliaEnvio('{{ envio.id }}')" id="btn-anomalia-envio-{{ envio.id }}"> <span class="ladda-label"><i class="fa fa-check"></i> Guardar</span><span class="ladda-spinner"></span></button>
                            </div>

                        </div>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <p style="border-bottom:1px solid #000000;"><strong>RECEPCIÓN DE LA VALIJA</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <div class="row col-md-12 m-b">

        <div class="col-md-4">
            <button class="ladda-button btn btn-primary" data-style="expand-left" onclick="recepcionarFactura({{noFactura}})" id="button_recepcionar_factura"> <span class="ladda-label"><i class="fa fa-check"></i> Recepcionar valijas</span><span class="ladda-spinner"></span></button>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
    <script src="{{ path('fos_js_routing_js',{ callback: 'fos.Router.setData' }) }}"></script>

    <script src="{{ asset('js/factura.js') }}"></script>

{% endblock %}